language: python
python:
- 3.8
install:
- pip install -U tox-travis
- pip install codecov
- pip install -r requirements.txt
script:
- tox
- coverage run -m pytest tests
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  on:
    repo: skyme5/snapchat-dl
    python: 3.8
  password:
    secure: WtP+k19agNeBKZ38GerUCUdA43KsSbTEGSXHkAqWX5cO+SdC9N8zrbR2DgvL/oXI+yVlVOEgTZGUfWxRJ4/MH/EQBdJZc8Tzz7dQkLecYOEPxkLYa66S1IbWF/EXfVQWWHQWMttQtcPXkDGUAENZA1nrfB/kbh1kHYxYV5+cwrxAlSg3mPrvHyEe2aMXrOVhhVG2yO4lb7m5EIaXQYi4Z+3WXqtMsQHH5uypukdDjWUW8z27WKMaumQLSI3vnaWwzRWDHGkFSwRsgOdBLe07j4AVkFgEUeuAvuY7pkWWpnRktF5JPlapcLq8nZF7mrz92EmGecjd5nOXVc04ZZyyU6zrl3pYZ+GXSJAzbMrk/YN6ILuhf+AMadLljm92MON+3gO7kEJEohW2iWZgnkNKOTw2ZMQ+JeSjakX8QUClfpMG2UwuIDOKl5CYbqUEBGgfckQfTuGd0io+sXTjIQzg70YuBf6dFS0z2qvpEr5QFHWAhQC4Ab8HPXhoGMmDjNmgicMgUkYDQ5lWZAWgEfEVvkvYyfHmcvEHjEcCqeEJCAuikyqBEL7RiYZ/3m0uoIVeNs3nQpFmh6pAPLtLv+Cb28hJ9LUcwBNRt67BHrWhjCsmRSWz4DmKuBWZxU6wU8T+HWJxnEaXiPM9EJCvNZrU1yJN7bqzcAbZmO1MPm9Gmy8=
after_success:
- codecov
